const express = require('express');
const router = express.Router();

router.get('/', (req, res) => {
  const theme = req.theme || 'light';
  const isDark = theme === 'dark';
  res.send(`
    <!DOCTYPE html>
    <html lang="en" data-theme="${theme}">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Express Demo · Mittal Domadiya (D24CS122)</title>
      <link rel="stylesheet" href="/styles.css">
    </head>
    <body class="${isDark ? 'dark' : 'light'}">
      <div class="container">
        <header>
          <h1>Express Demo</h1>
          <p class="byline">by <strong>Mittal Domadiya</strong> · <code>D24CS122</code></p>
        </header>
        <section>
          <p>Welcome! This page is generated by Express with a fresh layout and a couple of live API endpoints.</p>
          <ul class="features">
            <li>Live server time from <code>/api/time</code></li>
            <li>Health check at <code>/api/health</code></li>
            <li>Theme toggle (Light/Dark) via URL</li>
            <li>Request timing logs in the server console</li>
          </ul>
        </section>
        <section class="cards">
          <div class="card">
            <h2>Theme</h2>
            <p>Current: <strong id="themeLabel">${theme}</strong></p>
            <div class="actions">
              <a class="btn" href="/?theme=light">Light</a>
              <a class="btn" href="/?theme=dark">Dark</a>
            </div>
          </div>
          <div class="card">
            <h2>Server Time</h2>
            <p id="time">Loading…</p>
            <div class="actions">
              <button class="btn" id="refreshTime">Refresh Time</button>
            </div>
          </div>
          <div class="card">
            <h2>Health</h2>
            <pre id="health">Loading…</pre>
            <div class="actions">
              <button class="btn" id="refreshHealth">Check Health</button>
            </div>
          </div>
        </section>
        <footer>
          <small>© ${new Date().getFullYear()} Mittal Domadiya · D24CS122</small>
        </footer>
      </div>
      <script>
        async function fetchTime(){
          try {
            const res = await fetch('/api/time');
            const data = await res.json();
            document.getElementById('time').textContent = data.now + ' (' + data.tz + ')';
          } catch(e){ document.getElementById('time').textContent = 'Failed to load time'; }
        }
        async function fetchHealth(){
          try {
            const res = await fetch('/api/health');
            const data = await res.json();
            document.getElementById('health').textContent = JSON.stringify(data, null, 2);
          } catch(e){ document.getElementById('health').textContent = 'Failed to load health'; }
        }
        document.getElementById('refreshTime').addEventListener('click', fetchTime);
        document.getElementById('refreshHealth').addEventListener('click', fetchHealth);
        fetchTime();
        fetchHealth();
      </script>
    </body>
    </html>
  `);
});

module.exports = router;
